### PR TITLE
Bump to latest master

### PR DESCRIPTION
**Pull request by simonpasquier**
Same as https://github.com/openshift/prom-label-proxy/pull/151 but on top of the current openshift master to see if it helps with the CI.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
I think we have some more work to do in prow :thinking: 
```
2020/06/22 14:22:51 Container test in pod unit failed, exit code 2, reason Error
2020/06/22 14:22:51 No custom metadata found and prow metadata already exists. Not updating the metadata.
2020/06/22 14:22:52 Ran for 1m35s
```

**Comment by simonpasquier** [comment]
yes, the Go image automatically sets `GOFLAGS=-mod=vendor` which conflicts with the "upstream" Makefile doing the same dance... One solution is to not run the unit tests in the downstream fork (as we do for prometheus, alertmanager, node_exporter, ...).

Also `Dockerfile.ocp` needs to be updated too since the binary isn't at the same place.

**Comment by simonpasquier** [comment]
PR to remove unit tests from the CI: https://github.com/openshift/release/pull/9836

**Pull request closed without merging**
