### PR TITLE
Bump to latest master

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by lilic** [comment]
Is this the PR about unit tests you mentioned in the sync? Should we discuss it in the next arch call?

**Comment by s-urbaniak** [comment]
i see
```
error: some steps failed:
  * could not build execution graph: the following names were not found in the config or were duplicates: vendor (from [input:root], src, [input:base], prom-label-proxy, [output:stable:prom-label-proxy], e2e-aws, [input:ocp-4.5-upi-installer], [release:initial], [release:latest], [release-inputs], [images])
time="2020-06-23T07:06:27Z" level=info msg="Reporting job state \"failed\" with reason \"building_graph\""
```

**Comment by s-urbaniak** [comment]
but the error message is a mystery to me :thinking:

**Comment by s-urbaniak** [comment]
`unit` seems to fail with the same message.

**Pull request merged**
