### PR TITLE
vendor: sync vendor/ directory

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by paulfantom** [comment]
We should add a CI check to prevent `vendor/` directory from going stale. Same as we have in thanos repository.

**Comment by simonpasquier** [comment]
yes I've got a change ready for openshift/ci-tools.

**Comment by paulfantom** [comment]
> yes I've got a change ready for openshift/ci-tools.

Awesome. Just a nit: CI job configs go into [`openshift/release`](https://github.com/openshift/release/tree/master/ci-operator/config/openshift/prom-label-proxy) :)

**Comment by simonpasquier** [comment]
ETOOMANYREPOS :-)

**Comment by simonpasquier** [comment]
@paulfantom ping :smiley:

**Pull request merged**
